### PR TITLE
Make list of cards in final pdf customizable

### PR DESCRIPTION
**Pull request by fkz**
By adding some `\filter` command, that uses somewhat weird pgfkeys logic. 
We swallow the content of cards, that should not be visible, by looking for some `\end{cards}` (so this will break whenever we'll do recursive cards, but we should not do that). We only read ahead token by token (or group by group).

This allows to display only some cards by doing things like

```
\showCards{all} % show all cards
\showCards{title=Heal} % show all cards with Heal title
\showCards{title=Heal, level=1} % show all cards named "Heal" or that have level=1
\showCards{type=Spell} % show only spells
```

You can't really express everything, as the conditions are "OR"-ed together.

### CODE REVIEW

**Comment by Toxaris** [comment]
We can merge this if it helps with @fkz's workflow.

**Review by skaldarnar — APPROVED** [review]

**Comment by skaldarnar** [comment]
This could help with
> would be great if one could preview multiple cards at once…
> This could even be a pre-defined set to show the full range of card types and features we use…
>
> `/show-preview` or `/preview-deck` or something like that

**Comment by fkz** [comment]
I want to have faster compile times, and also be able to just work on a specific card without having to find it in the increasingly bigger pdf.
I don't particularly like the "filter language" currently, I wonder if pgfkeys is really a good fit here anyway.
But let's merge this and improve later :)

**Comment by fkz** [comment]
Not sure how much this helps with the "/show" command.
It currently works by matching the bookmarks in the generated pdf, as that is faster than calling latex (which is slow mostly because it first needs to download the whole of TeXLive).

**Pull request merged**
