### PR TITLE
feat: render box for current HP

### PR DESCRIPTION
**Pull request by skaldarnar**
The hit points are a mutable value that changes during gameplay. Thus, add a box with space for the player to write down the current hit points.

```tex
\HitPoints[20]
```
image

```tex
\HitPoints
```
image

### CODE REVIEW

**Comment by fkz** [comment]
I wonder if this compiles with the latest main (the abbreviation card), so we should rettigger a check run, but it appears that's not possible without changing the PR itself. @skaldarnar can you rebase on main maybe?

**Comment by skaldarnar** [comment]
@fkz looks as funny as you would expect...

image

I guess I should makes this a `\NewDocumentCommand` and check whether we get arguments or not...

**Comment by fkz** [comment]
Ah, I was afraid it wouldn't even compile. So maybe we just merge it? At some point we can think about how to organize the abbreviation card better.

**Review by fkz — APPROVED** [review]

**Comment by skaldarnar** [comment]
image

Turning this into a `\NewDocumentCommand` is straight forward (after moving all the commands over to `symbols.tex`. Not sure where the different spacing comes from, though… 🤔 

image

**Pull request merged**
