### PR TITLE
Put the title a bit higher on the card

### PR DESCRIPTION
**Pull request by fkz**

### CODE REVIEW

**Comment by fkz** [comment]
resulting look: /show Breastplate

**Comment by fkz** [comment]
Unfortunately, for long titles it doesn't look so great: /show Minor Healing Potion

**Comment by fkz** [comment]
test

**Comment by fkz** [comment]
test2

**Comment by fkz** [comment]
Show 2 cards in one go:
/show Breastplate
/show Minor Healing Potion

**Comment by Toxaris** [comment]
I think we should break long titles into one title line + one subtitle line. In this case:

> Healing Potion
> (Minor)

This will be even more significant if people print custom cards for their crazy weapons at higher levels:

> Uranium Long Sword
> (+3 Greater Striking Flaming Intelligent Cursed)

**Comment by Toxaris** [comment]
Current main branch (as of 047d0d6e91b595b86b8e5acca6f8531880cf0f10):

image


With this PR:

image

Unsure what is better :(

**Comment by skaldarnar** [comment]
I liked that the "CRB 123" reference was on the same baseline as the title, and the corner background also aligned with the font.

image

With this change, the baseline of the title, the colored corner element, the card type are all different:

image

btw, I started with https://github.com/potsdam-pnp/pf2e-cards/blob/main/card-template.svg to allow to play around with layouts and alignment in Inkscape more freely.

**Comment by Toxaris** [comment]
Makes sense. So I would propose to close this without merging.

**Comment by fkz** [comment]
Let's close this then.

**Comment by fkz** [comment]
> With this change, the baseline of the title, the colored corner element, the card type are all different:

Yes this is because the two em's with the + and - are different because of different font size, I think. I made this because the space to the border was a bit too tiny, but with the current main, we don't need this anymore.

**Pull request closed without merging**
