### PR TITLE
color-palette: Nord

### PR DESCRIPTION
**Pull request by skaldarnar**
Based on https://www.nordtheme.com/ and https://lospec.com/palette-list/nord-theme.

image

Contributes to #42.

### CODE REVIEW

**Comment by skaldarnar** [comment]
Rule: /show Bulk

**Comment by skaldarnar** [comment]
Action: /show Demoralize

**Comment by skaldarnar** [comment]
Condition: /show Encumbered

**Comment by skaldarnar** [comment]
Item: /show Repair Kit

**Comment by skaldarnar** [comment]
Cantrip: /show Acid Splash

**Comment by skaldarnar** [comment]
Focus: /show Force Bolt

**Comment by skaldarnar** [comment]
Cantrip: /show Acid Splash

**Comment by skaldarnar** [comment]
Spell: /show Heal

**Comment by Toxaris** [comment]
I decided to merge the competing PR https://github.com/potsdam-pnp/pf2e-cards/pull/53 in time for printing the cards for the next session :)

**Pull request closed without merging**
