### PR TITLE
Add a checks workflow

### PR DESCRIPTION
**Pull request by fkz**
This adds annotations for LateX errors and warnings, including overflows and underflows.

### CODE REVIEW

**Review by skaldarnar — APPROVED** [review]
I like, but I don't know whether all these warnings are helpful, especially the overrides based on different imports...

**Comment by fkz** [comment]
Yeah, these warnings are not helpful, but according to https://tex.stackexchange.com/a/584866 can be suppressed.

 ```
\usepackage[warnings-off={mathtools-colon,mathtools-overbracket}]{unicode-math}
```

**Comment by fkz** [comment]
Hm. when compiling locally, I also don't see these warnings 🤔

**Comment by fkz** [comment]
Tested in #20 and it works to supress these 2 warnings.

I wonder if we should merge this:
- ➕ warnings are visible in PRs
- ➖ it might clutter the "files changed" view in PRs when information, that is not related to this PR is shown there

**Comment by fkz** [comment]
I think I could also implement showing only warnings that are new (that is the exact warning is not like it was in the base commit). But this would break when refactoring things so line numbers or file names change 🤔 .

**Pull request merged**
